---
version: 1
update_configs:
- package_manager: "ruby:bundler"
  directory: "/"
  update_schedule: "live"
  version_requirement_updates: increase_versions
- package_manager: "submodules"
  directory: "/"
  update_schedule: "daily"
